version: '3.8'

networks:
  rabbitmq:
    ipam:
      config:
        - subnet: "120.28.0.0/16"
        
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - rabbitmq
      
volumes:
    logs-folder:
        name: ${log_rabbitmq_management}
        driver: local
